Carbon:
  IncludeAssetsCache:
    enableFileWatcher: true

    # Can be an array of package keys or a single package key (string)
    restrictToPackages: null

    directories:
      # The key is the fileextension, the value is the path to the directory
      # ALL tracks all file extensions
      # A value can be an string or an array of paths

      ALL: Private/Templates/InlineAssets
      css: Public/Styles
      js: Public/Scripts
      mjs: Public/Modules
